######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 8 08:39:43 2017
######################################################################

TEMPLATE = app
TARGET = ai_assignment_bayes
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += mydialog.h sample.h jhparser.h jhbayes.h
SOURCES += mydialog.cpp sample.cpp jhparser.cpp jhbayes.cpp main.cpp
RESOURCES += application.qrc
